[package]
name = "enmacompat"
version = "0.1.0"
edition = "2021"

[dependencies]
binrw = "0.13"
clap = { version = "4.5.4", features = ["derive"] }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
